### ISSUE TITLE
Set Device class for 'Volume' sensor

### ISSUE THREAD

**Issue by SirJohnDoe** [golles/ha-kamstrup_403#103]
### Did you read the instructions?

- [X] I have read the [README](../blob/master/README.md).

### The request

First of all thank you for this integration, it works great.

One small suggestion I have:
By default the 'Heat Energy (E1)' and 'Volume' sensors are activated. The former can now be used in the Energy dashboard, but the 'Volume' sensor cannot be used, because the Device class is missing. I'd like to monitor the Volume as well in the dashboard through the 'Water consumption' dashboard, because I don't have a Cold water meter, so I might as well show this.

So my request: could you add the volume Device class to the Volume sensor?

The 'Heat energy to gas' [section](https://github.com/golles/ha-kamstrup_403/tree/main#heat-energy-to-gas) can probably also be removed from the Readme, as the energy dashboard now supports Gas sensors with GJ unit. Or the section and sensor can be kept but with a proper conversion: according to [this blog](https://www.pieterbrinkman.com/2022/02/01/make-your-city-heating-stadsverwarming-smart-and-connect-it-home-assistant-energy-dashboard/) the GJ should be multiplied by 32 to get the m3 gas equivalent. After searching a bit more I see that it's actually 31,6 according to [this](https://www.infomil.nl/onderwerpen/duurzaamheid-energie/energiebesparing/vragen-antwoorden/overige-vragen/omrekening-verbruik/) Dutch government website.

![image](https://github.com/golles/ha-kamstrup_403/assets/11654657/ad228edf-06b9-4847-8511-ce164bf95e97)

Thanks!

**Comment by golles** [comment]
Hi @SirJohnDoe thanks for your message.

> One small suggestion I have:
By default the 'Heat Energy (E1)' and 'Volume' sensors are activated. The former can now be used in the Energy dashboard, but the 'Volume' sensor cannot be used, because the Device class is missing. I'd like to monitor the Volume as well in the dashboard through the 'Water consumption' dashboard, because I don't have a Cold water meter, so I might as well show this.
> So my request: could you add the volume Device class to the Volume sensor?

I'm not quite sure if the city heating volume should be considered as water usage.

> The 'Heat energy to gas' [section](https://github.com/golles/ha-kamstrup_403/tree/main#heat-energy-to-gas) can probably also be removed from the Readme, as the energy dashboard now supports Gas sensors with GJ unit. Or the section and sensor can be kept but with a proper conversion: according to [this blog](https://www.pieterbrinkman.com/2022/02/01/make-your-city-heating-stadsverwarming-smart-and-connect-it-home-assistant-energy-dashboard/) the GJ should be multiplied by 32 to get the m3 gas equivalent. After searching a bit more I see that it's actually 31,6 according to [this](https://www.infomil.nl/onderwerpen/duurzaamheid-energie/energiebesparing/vragen-antwoorden/overige-vragen/omrekening-verbruik/) Dutch government website.

I'm on HA 2023.9.2 and I can't add the E1 sensor to the gas usage section, it can be added in the individual devices block, however, that doesn't provide a nice overview of the usage. The gas section has a much nicer graph.

It was a deliberate decision to have a 1:1 conversation for the E1 sensor to gas, even though this is not the right way to convert GJ to gas, it does provide an easy way to see your usage and compare that with your meter.

**Comment by SirJohnDoe** [comment]
Hmm fair enough, not sure what exactly the water volume measures. If it's just water flowing through the system it's not that useful.

As for using the GJ sensor, Heat Energy (E1), I can select it in the latest HA. It was added last year: https://github.com/home-assistant/core/pull/80870

![image](https://github.com/golles/ha-kamstrup_403/assets/11654657/5bd1cb4c-0cef-4df0-9e6b-eb1af2af99e9)
