### ISSUE TITLE
Can it be used for newer meters.Kamstrup 603 / 803

### ISSUE THREAD

**Issue by Bluhme1** [golles/ha-kamstrup_403#2]
I am waiting for my Stromzähler, Smart Meter IR (Infrarot) Schreib / Lesekopf USB (Optokopf) to arrive, so I haven't
done any testing yet.
My heating company is planning to replace my meter with the Kamstrup 603 series. Will this component be able  to read data from that meter also? Will it require modifications?
And thank you for your work

best wishes
Lars. Denmark

**Comment by golles** [comment]
Hi Lars,

I wouldn't dare to say if this will work or not. The meter looks from the outside similar, so it's worth trying...
Via via I got hold of this file, to read the meter values: https://github.com/golles/ha-kamstrup_403/blob/main/custom_components/kamstrup_403/kamstrup.py
And here you can find the specific sensors (command) https://github.com/golles/ha-kamstrup_403/blob/main/custom_components/kamstrup_403/const.py#L14-L74 

I did consider adding support for multiple meters, also because I had a component for my previous meter https://github.com/golles/Home-Assistant-Sensor-MC66C but the difficult part here is, that I only have one specific meter and I couldn't test changes for other models.

Let me know when you got the IR reader and how it works out.

**Comment by jossie67** [comment]
Hi, 
Will this also work on a Kamstrup 401 and a  Lesekopf USB (Optokopf)?

Thanks
Jos

**Comment by golles** [comment]
> Hi,
> Will this also work on a Kamstrup 401 and a Lesekopf USB (Optokopf)?
> 
> Thanks
> Jos

The core class suggests it works for 402 https://github.com/golles/ha-kamstrup_403/blob/main/custom_components/kamstrup_403/kamstrup.py#L12 but I've only tested it on a 403. If those meters have the same protocol, they should work. About that IR reader, the specs look like it should work.
Please give it a try and let me know

**Comment by golles** [comment]
Hi Lars, what do you suggest that we do with this issue? Have you tried this component on the 603/803 meter?

**Comment by golles** [comment]
In that case, I close this issue for now, as there is nothing I can do.
Feel free to reopen or comment here once you got it.

Or feel free to drop an email again.

**Comment by jesperholstjh** [comment]
@Bluhme1 Hi Lars. Did you get it working on your Multical 603?

Best regards, Jesper (DK)
