### ISSUE TITLE
Kamstrup multical 21 water meter

### ISSUE THREAD

**Issue by kristianschneider** [golles/ha-kamstrup_403#67]
### Meter

Multical 21

### More info

A python script got the multical integration via this PR: [https://github.com/bsdphk/PyKamstrup/pull/6](https://github.com/bsdphk/PyKamstrup/pull/6)

**Comment by jakobschou** [comment]
Since this issue has been closed, does that mean this HA integration works with the water meter aswell?

**Comment by kristianschneider** [comment]
Nope. It never happened.
But I forked this and made
https://github.com/kristianschneider/ha-multical_21

**Comment by jakobschou** [comment]
Wonderful!
I will try your component then!

**Comment by golles** [comment]
Nice work on your fork!
Looking at the diff, it only seems that this integration is missing sensor V1Reverse (243)

**Comment by jakobschou** [comment]
@kristianschneider 
I have just received the USB to IR, and tried to attach it to my FlowIQ 2200.

I got two m3 reading in HA, by trial and error, but now it does not read anymore.

Do you still have yours attached and how did you do it?

**Comment by kristianschneider** [comment]
Hi Jakob.
It is not attached as per say, but basically just resting on the meter. 
I plan on creating a 3D printable bracket at some point.

It has been running for a couple of months now without any issues.
On your home assistant device perhaps try and do a **dmesg** and see if the USB disconnects or something.
If you are using a rasperry pi ensure that the powersupply is big enough.

**Comment by jakobschou** [comment]
Hi again,

I have now tried to remove and install the module again, in different orientation with the reader on the meter, and got it working again - this run lasted 3-4 readings over 3 hours.

Beside that, I have attached 2 additional magnets to the top end of the meter, and the display changes if interferred with (so I guess it puts the meter into some kind of reading mode).

But now again, the state in HA becomes 'Unknown' after a few hours.

The reader is connected to a RPi 4  running only HA with the original power supply 5,1V = 3,0A.

So is this due to the power supply is too small or that HA disconnects the USB somehow?

**Comment by kristianschneider** [comment]
with 3A you should be ok.
It sounds like a hardware issue somehow. I would check the logs on your Pi. 
You could also try and enable debugging to see if something meaningful shows up in the HA log
![image](https://github.com/golles/ha-kamstrup_403/assets/6593720/58c0ef9f-eb52-430d-8192-f7d60ba4ead5)

**Comment by DBHAHA** [comment]
> Hi Jakob. It is not attached as per say, but basically just resting on the meter. I plan on creating a 3D printable bracket at some point.
> 
Hi Kristian. Thank you the repository, it saved my day :-) Did ever create a bracket for the Multical 21?
