### ISSUE TITLE
Multiple device support

### ISSUE THREAD

**Issue by hepfister** [golles/ha-kamstrup_403#9]
### Did you read the instructions?

- [X] I have read the [README](../blob/master/README.md).

### The request

Hi Sander, I own a Kamstrup 401 and kinda hoped that your plugin would work out of the box for this one too. Unfortunately it does not. Is it possible to add support for the 401? 

Groet, 
Hugo

**Comment by golles** [comment]
Hi Hugo,
I understand your request, but that would be impossible to do for me. Simply because I don't have such a meter myself.
That's also why I've stopped development for my old meter https://github.com/golles/Home-Assistant-Sensor-MC66C.

You could fork this repo and implement the meter-specific changes in `kamstrup.py` yourself.

**Comment by hepfister** [comment]
Sounds like configuring more than programming so I'll give it a shot. Thanks for the suggestion.

**Comment by hepfister** [comment]
Ticket can be closed
